core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.get_main_page, name='main'),
    path('groups/', views.GroupList.as_view(), name='groups'),
    path('courses/', views.CourseList.as_view(), name='courses'),
    path('users/', views.UserList.as_view(), name='users'),
    path('user_detail/<int:pk>', views.UserDetail.as_view(), name='user_detail'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_delete/<int:pk>', views.UserDelete.as_view(), name='user_delete'),
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'),
]

itcode_12/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class User(models.Model):
    name = models.CharField(max_length=40)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='Группа')
    course = models.ManyToManyField(Course, verbose_name='Курсы')

core/forms.py
from django import forms

from core import models

class UserForm(forms.ModelForm):
    name = forms.CharField(label='Имя', required=True)

    def clean_name(self):
        name = self.cleaned_data['name']
        if name.isnumeric():
            raise forms.ValidationError('Имя не должно состоять только из чисел')
        return name

    class Meta:
        model = models.User
        fields = '__all__'

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from core import models, forms


# Create your views here.
class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.get_title()
        return context


class GroupList(TitleMixin, ListView):
    model = models.Group
    template_name = 'groups.html'
    context_object_name = 'groups'
    title = 'Группы'


class CourseList(TitleMixin, ListView):
    model = models.Course
    template_name = 'courses.html'
    context_object_name = 'courses'
    title = 'Курсы'


class UserList(TitleMixin, ListView):
    model = models.User
    template_name = 'users.html'
    context_object_name = 'users'
    title = 'Пользователи'


class UserDetail(TitleMixin, DetailView):
    model = models.User
    template_name = 'user_detail.html'
    context_object_name = 'user'
    title = 'Профиль пользователя'


class UserCreate(TitleMixin, CreateView):
    model = models.User
    template_name = 'user_create.html'
    form_class = forms.UserForm
    title = 'Создание пользователя'
    success_url = reverse_lazy('core:users')


class UserDelete(TitleMixin, DeleteView):
    model = models.User
    template_name = 'user_delete.html'
    fields = "__all__"
    title = 'Удаление пользователя'
    success_url = reverse_lazy('core:users')


class UserUpdate(TitleMixin, UpdateView):
    model = models.User
    template_name = 'user_update.html'
    fields = "__all__"
    title = 'Изменение пользователя'
    success_url = reverse_lazy('core:users')


def get_main_page(request):
    return render(request=request, template_name='main.html', context={'title': 'Главная'})

core/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link href="{% static 'css/head.css' %}" rel="stylesheet">
</head>
<body>
<div class="navbar">
    <nav>
        <ul>
            <li><a href="{% url 'core:main' %}">Главная</a></li>
            <li><a href="{% url 'core:groups' %}">Группы</a></li>
            <li><a href="{% url 'core:courses' %}">Курсы</a></li>
            <li>
                <div class="dropdown">
                    <button class="dropdown-button">Пользователи</button>
                    <div class="dropdown-content">
                        <a href="{% url 'core:users' %}">Список пользователей</a>
                        <a href="{% url 'core:user_create' %}">Создать пользователя</a>
                    </div>
                </div>
            </li>
        </ul>
    </nav>
</div>
<main>
    {% block content %}{% endblock %}
</main>
</body>
</html>

core/templates/courses.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <h1>Список курсов</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.pk }}</td>
                    <td>{{ course.name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

core/templates/groups.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <h1>Список групп</h1>
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
            </tr>
            </thead>
            <tbody>
            {% for group in groups %}
                <tr>
                    <td>{{ group.pk }}</td>
                    <td>{{ group.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

core/templates/main.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <h1>Главная</h1>
{% endblock %}

core/templates/user_create.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}<
{% block content %}
    <h1>Создание пользователя</h1>
    <form action="{% url 'core:user_create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
        <br>
        <a href="{% url 'core:users' %}">Вернуться</a>
    </form>
{% endblock %}

core/templates/user_delete.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}<
{% block content %}
    <h1>Удалить пользователя {{ user.name }}?</h1>
    <form action="{% url 'core:user_delete' user.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Удалить</button>
        <br>
        <a href="{% url 'core:users' %}">Вернуться</a>
    </form>
{% endblock %}

core/templates/user_detail.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <h1>Профиль пользователя - {{ user.name }}</h1>
    <h3>Группа пользователя - {{ user.group.name }}</h3>
    <h3>Количество курсов -  {{user.course.count}}</h3>
    Курсы:
    <ul>
        {% for course in user.course.all %}
            <li>
                {{ course.name }}
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'core:users' %}">Вернуться</a>
{% endblock %}

core/templates/user_update.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <h1>Обновление аккаунта пользователя {{ user.name }}</h1>
    <form action="{% url 'core:user_update' user.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Обновить</button>
        <br>
        <a href="{% url 'core:users' %}">Вернуться</a>
    </form>
{% endblock %}

core/templates/users.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <h1>Список пользователей</h1>
    <table>
          <thead>
          <tr>
              <th>ID</th>
              <th>Имя</th>
          </tr>
          </thead>
          <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.pk }}</td>
                    <td>{{ user.name }}</td>
                    <td><a href="{% url 'core:user_detail' user.pk %}">Подробнее</a></td>
                    <td><a href="{% url 'core:user_delete' user.pk %}">Удалить</a></td>
                    <td><a href="{% url 'core:user_update' user.pk %}">Изменить</a></td>
                </tr>
            {% endfor %}
          </tbody>
      </table>
{% endblock %}